MyFinance/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='main'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path('statistics/', include('site_statistics.urls', namespace='statistics')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounting/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from accounting.views import (
    ExpensesUnitListView, ExpensesUnitCreateView, ExpensesUnitUpdateView,
    IncomeUnitCreateView, IncomeUnitUpdateView, IncomeUnitListView,
    UnitListView, AccountingDownloadView,
    CategoryCreateView, CategoryUpdateView, CategoryListView, CategoryDetailView,
    )

app_name = 'accounting'
urlpatterns = [
    path('', UnitListView.as_view(), name='unit-list'),

    path('expenses/', ExpensesUnitListView.as_view(), name='expenses-unit-list'),
    path('expenses_new/', ExpensesUnitCreateView.as_view(), name='expenses-unit-create'),
    path('expenses_edit/<int:pk>', ExpensesUnitUpdateView.as_view(), name='expenses-unit-update'),
    path('income/', IncomeUnitListView.as_view(), name='income-unit-list'),
    path('income_new/', IncomeUnitCreateView.as_view(), name='income-unit-create'),
    path('income_edit/<int:pk>', IncomeUnitUpdateView.as_view(), name='income-unit-update'),

    path('download/<str:format>', AccountingDownloadView.as_view(), name='unit-download'),

    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('category_new/', CategoryCreateView.as_view(), name='category-create'),
    path('category_edit/<int:pk>', CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path

from accounts.views import RegistrationView, LoginView, LogoutView, AccountUpdateView, AccountDetailView

app_name = 'accounts'
urlpatterns = [
    path('', AccountDetailView.as_view(), name='account-detail'),
    path('update/', AccountUpdateView.as_view(), name='account-update'),
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

accounting/models.py
from django.db import models
from django.utils.functional import cached_property

from django_extensions.db.models import TimeStampedModel


class Category(TimeStampedModel):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class AccountingUnitManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().prefetch_related('categories')


class AccountingUnit(TimeStampedModel):
    name = models.CharField(max_length=64)
    quantity = models.PositiveIntegerField(default=1)
    objects = AccountingUnitManager()

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class ExpensesUnit(AccountingUnit):
    price = models.DecimalField(max_digits=8, decimal_places=2)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    purchase_date = models.DateField()
    categories = models.ManyToManyField('Category', related_name='expenses_unit', blank=True)

    @cached_property
    def calculate_total_price(self):
        return self.quantity * self.price

    def save(self, **kwargs):
        self.total_price = self.calculate_total_price
        return super().save(**kwargs)


class IncomeUnit(AccountingUnit):
    income = models.DecimalField(max_digits=8, decimal_places=2)
    total_income = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    receive_date = models.DateField()
    categories = models.ManyToManyField('Category', related_name='income_unit', blank=True)

    @cached_property
    def calculate_total_income(self):
        return self.quantity * self.income

    def save(self, **kwargs):
        self.total_income = self.calculate_total_income
        return super().save(**kwargs)

accounting/forms.py
from django import forms
from accounting.models import ExpensesUnit, IncomeUnit, Category


class ExpensesUnitForm(forms.ModelForm):
    price = forms.DecimalField(widget=forms.TextInput(attrs={'placeholder': '0.00', 'numval': ''}))
    purchase_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    quantity = forms.IntegerField(initial=1, widget=forms.TextInput(attrs={'numval': ''}))

    class Meta:
        model = ExpensesUnit
        exclude = ['created', 'modified', 'total_price']

    def clean_quantity(self):
        data = self.cleaned_data['quantity']
        if data < 1:
            raise forms.ValidationError('Can be 1 or greater.')

        return data


class IncomeUnitForm(forms.ModelForm):
    income = forms.DecimalField(widget=forms.TextInput(attrs={'placeholder': '0.00', 'numval': ''}))
    receive_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    quantity = forms.IntegerField(initial=1, widget=forms.TextInput(attrs={'numval': ''}))

    class Meta:
        model = IncomeUnit
        exclude = ['created', 'modified', 'total_income']

    def clean_quantity(self):
        data = self.cleaned_data['quantity']
        if data < 1:
            raise forms.ValidationError('Can be 1 or greater.')

        return data


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

accounting/views.py
from typing import Callable
from itertools import chain

from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.http import JsonResponse, HttpRequest, HttpResponse

from accounting.models import ExpensesUnit, IncomeUnit, Category
from accounting.forms import ExpensesUnitForm, IncomeUnitForm, CategoryForm
from accounting import utils


class RelatedCategoryMixin:
    """Mixin for creating categories on accounting page."""
    categories = []

    def post(self, request, *args, **kwargs):
        if utils.is_ajax(request):
            category = Category.objects.create(name=request.POST.get('name'))
            self.categories.append(category)
            return JsonResponse({'id': category.id})

        return super().post(request, *args, **kwargs)


class SingleObjectSearchMixin:
    """Mixin for searching and ordering on a model."""
    model_dict: dict = None
    filters: dict = None
    ordering: str = None

    def get_queryset(self):
        request_data = self.request.GET
        values = {}
        model = None

        for key in request_data:
            if not request_data[key]:
                continue
            
            if key.startswith('model') and self.model_dict:
                model = self.model_dict.get(request_data[key])
            elif key.startswith('order_by'):
                self.ordering = request_data[key]
            elif self.filters[key].endswith('__in'):
                values[self.filters[key]] = request_data.getlist(key)
            else:
                values[self.filters[key]] = request_data[key]

        if model:
            queryset = model.objects.filter(**values).order_by(self.ordering).distinct()
        else:
            queryset = self.model.objects.filter(**values).order_by(self.ordering).distinct()

        return queryset


class ExpensesUnitCreateView(RelatedCategoryMixin, CreateView):
    template_name = 'accounting/unit_create.html'
    model = ExpensesUnit
    form_class = ExpensesUnitForm
    success_url = reverse_lazy('accounting:expenses-unit-list')


class IncomeUnitCreateView(RelatedCategoryMixin, CreateView):
    template_name = 'accounting/unit_create.html'
    model = IncomeUnit
    form_class = IncomeUnitForm
    success_url = reverse_lazy('accounting:income-unit-list')


class ExpensesUnitUpdateView(RelatedCategoryMixin, UpdateView):
    template_name = 'accounting/unit_update.html'
    model = ExpensesUnit
    form_class = ExpensesUnitForm
    success_url = reverse_lazy('accounting:expenses-unit-list')


class IncomeUnitUpdateView(RelatedCategoryMixin, UpdateView):
    template_name = 'accounting/unit_update.html'
    model = IncomeUnit
    form_class = IncomeUnitForm
    success_url = reverse_lazy('accounting:income-unit-list')


class UnitListMixin:
    """Mixin for all UnitListView classes."""

    filters = {
        'name': 'name__icontains',
        'quantity': 'quantity',
        'created': 'created__date',
        'categories': 'categories__name__in',
        'total_price': 'total_price',
        'total_income': 'total_income',
        'purchase_date': 'purchase_date',
        'receive_date': 'receive_date',
        }

    ordering = '-created'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()

        return context


class UnitListView(UnitListMixin, SingleObjectSearchMixin, ListView):
    template_name = 'accounting/unit_list.html'
    model = IncomeUnit
    model_dict = {'expenses': ExpensesUnit, 'income': IncomeUnit}
    context_object_name = 'unit_list'


class ExpensesUnitListView(UnitListMixin, SingleObjectSearchMixin, ListView):
    template_name = 'accounting/expenses_unit_list.html'
    model = ExpensesUnit


class IncomeUnitListView(UnitListMixin, SingleObjectSearchMixin, ListView):
    template_name = 'accounting/income_unit_list.html'
    model = IncomeUnit


class AccountingDownloadView(ListView):
    """View for downloading Accounting data."""
    def get(self, request, *args, **kwargs):
        func_name: str = f'dump_to_{kwargs.get("format", "xlsx")}'
        statistics_func: Callable[[HttpRequest], dict] = getattr(utils, func_name)
        statistics_data = statistics_func(request)

        with open(statistics_data.get('full_path'), 'rb') as f:
            response = HttpResponse(f.read(), content_type=statistics_data.get('content_type'))
            response['Content-Disposition'] = f'filename={statistics_data.get("content_disposition")}'

        return response


class CategoryCreateView(CreateView):
    template_name = 'accounting/category_create.html'
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('accounting:category-list')


class CategoryUpdateView(UpdateView):
    template_name = 'accounting/category_update.html'
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('accounting:category-list')


class CategoryListView(SingleObjectSearchMixin, ListView):
    template_name = 'accounting/category_list.html'
    model = Category

    filters = {
        'name': 'name__icontains',
        'created': 'created__date',
        }

    ordering = 'created'


class CategoryDetailView(DetailView):
    template_name = 'accounting/category_detail.html'
    model = Category

templates/accounting/category_create.html
{% extends "base.html" %}

{% block title %}New category{% endblock %}

{% block content %}
    {% load bootstrap4 %}

    <div class="container">
        <div class="py-3">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                    Save
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

templates/accounting/category_detail.html
{% extends "base.html" %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="d-flex justify-content-end">
            <a href="{% url 'accounting:category-update' pk=category.pk %}">edit</a>
        </div>
        <ul class="list-group">
            <li class="list-group-item">{{ category.name }}</li>
        </ul>
    </div>
{% endblock %}

templates/accounting/category_list.html
{% extends "base.html" %}

{% block title %}Categories{% endblock %}

{% block content %}
{% load static %}
{% load table_sort %}
    <div class="container">
        <!-- Table -->
        <div class="py-3">
            <table class="table table-bordered table-hover">
                <div class="row">
                    <h4 style="padding-left: 0.65em; margin-top: 7px;">Categories</h4>
                    <div class="col my-auto" style="padding-left: 0.5em;">
                        <a href="{% url 'accounting:category-create' %}" class="btn btn-primary btn-sm" style="width: 30px; height: 30px; outline: none; box-shadow: none;">
                            +
                        </a>
                    </div>
                </div>
                <!-- Search -->
                <div class="container" style="padding: 0; padding-bottom: 1em;">
                    <form id="id_search_form" method="get"">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Name</label>
                                <input type="text" class="form-control" name="name">
                            </div>
                            <div class="form-group col-md-6">
                                <label>Created</label>
                                <input type="date" class="form-control" name="created">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Search</button>
                        <a class="btn btn-light" href="{% url 'accounting:category-list' %}" style="background-color: rgb(238, 238, 238);">Show all</a>
                    </form>
                </div>
                <!-- End search -->
                <thead class="thead-light">
                    <tr>
                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'name' '-' %}">Name
                                <img src="{% get_arrow request 'name' %}">
                            </a>
                        </th>
                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'created' '-' %}">Created
                                <img src="{% get_arrow request 'created' %}">
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in category_list %}
                    <tr>
                        <td>
                            <a style="color: inherit;" href="{% url 'accounting:category-update' pk=category.pk %}">
                                {{ category.name }}
                            </a>
                        </td>
                        <td>
                            <a style="color: inherit;" href="{% url 'accounting:category-update' pk=category.pk %}">
                                {{ category.created }}
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- End table -->
        <link href="{% static 'select2-4.1.0-rc.0/css/select2.min.css' %}" rel="stylesheet"/>
        <script src="{% static 'select2-4.1.0-rc.0/js/select2.min.js' %}"></script>
        <script src="{% static 'js/validate-numeric.js' %}"></script>
    </div>
{% endblock %}

templates/accounting/category_update.html
{% extends "base.html" %}

{% block title %}Update category{% endblock %}

{% block content %}
    {% load bootstrap4 %}

    <div class="container">
        <div class="py-3">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                    Save
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

templates/accounting/expenses_unit_list.html
{% extends "base.html" %}

{% block title %}Expenses{% endblock %}

{% block content %}
{% load static %}
{% load table_sort %}
    <div class="container">
        
        <!-- Top buttons -->
        <div class="py-3">
            <div class="row">
                <h4 style="padding-left: 0.65em; margin-top: 7px;">Expenses</h4>
                <div class="col my-auto" style="padding-left: 0.5em;">
                    <a href="{% url 'accounting:expenses-unit-create' %}" class="btn btn-primary btn-sm" style="width: 30px; height: 30px; outline: none; box-shadow: none;">
                        +
                    </a>
                    <div class="btn-group" style="padding-left: 0.5em;">
                        <button type="button" class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Export
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'accounting:unit-download' format='xlsx' %}?model=expenses">XLSX</a>
                            <a class="dropdown-item" href="{% url 'accounting:unit-download' format='csv' %}?model=expenses">CSV</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End top buttons -->

            <!-- Search -->
            <div class="container" style="padding: 0; padding-bottom: 1em;">
                <form id="id_search_form" method="get">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Price</label>
                            <input type="text" class="form-control" name="total_price" numval>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Purchase date</label>
                            <input type="date" class="form-control" name="purchase_date">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Created</label>
                            <input type="date" class="form-control" name="created">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Categories</label>
                        <select id="id_categories" class="form-control" name="categories" multiple>
                            {% for category in categories %}
                                <option>{{ category }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                    <a class="btn btn-light" href="{% url 'accounting:expenses-unit-list' %}">Show all</a>
                </form>
            </div>
            <!-- End search -->

            <!-- Table -->
            <table id="table" class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'name' '-' %}">Name
                                <img src="{% get_arrow request 'name' %}">
                            </a>
                        </th>

                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'quantity' '-' %}">Quantity
                                <img src="{% get_arrow request 'quantity' %}">
                            </a>
                        </th>

                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'total_price' '-' %}">Price
                                <img src="{% get_arrow request 'total_price' %}">
                            </a>
                        </th>

                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'purchase_date' '-' %}">Purchase date
                                <img src="{% get_arrow request 'purchase_date' %}">
                            </a>
                        </th>

                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'created' '-' %}">Created
                                <img src="{% get_arrow request 'created' %}">
                            </a>
                        </th>

                        <th scope="col">Categories</th>
                    </tr>
                </thead>
                <tbody>
                    {% for unit in expensesunit_list %}
                    <tr>
                        <td>
                            <a href="{% url 'accounting:expenses-unit-update' pk=unit.pk %}">
                                {{ unit.name }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'accounting:expenses-unit-update' pk=unit.pk %}">
                                {{ unit.quantity }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'accounting:expenses-unit-update' pk=unit.pk %}">
                                ${{ unit.total_price }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'accounting:expenses-unit-update' pk=unit.pk %}">
                                {{ unit.purchase_date }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'accounting:expenses-unit-update' pk=unit.pk %}">
                                {{ unit.created }}
                            </a>
                        </td>
                        <td>
                            {% for category in unit.categories.all %}
                                <a class="category" href="{% url 'accounting:category-detail' pk=category.pk %}">
                                    <span class="badge badge-info">{{ category }}</span>
                                </a>
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- End table -->
        
        <link href="{% static 'select2-4.1.0-rc.0/css/select2.min.css' %}" rel="stylesheet"/>
        <script src="{% static 'select2-4.1.0-rc.0/js/select2.min.js' %}"></script>
        <script src="{% static 'js/select2-init.js' %}"></script>
        <script src="{% static 'js/validate-numeric.js' %}"></script>
    </div>
{% endblock %}

templates/accounting/income_unit_list.html
{% extends "base.html" %}

{% block title %}Income{% endblock %}

{% block content %}
{% load static %}
{% load table_sort %}
    <div class="container">
        
        <!-- Top buttons -->
        <div class="py-3">
            <div class="row">
                <h4 style="padding-left: 0.65em; margin-top: 7px;">Income</h4>
                <div class="col my-auto" style="padding-left: 0.5em;">
                    <a href="{% url 'accounting:income-unit-create' %}" class="btn btn-primary btn-sm" style="width: 30px; height: 30px; outline: none; box-shadow: none;">
                        +
                    </a>
                    <div class="btn-group" style="padding-left: 0.5em;">
                        <button type="button" class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Export
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'accounting:unit-download' format='xlsx' %}?model=income">XLSX</a>
                            <a class="dropdown-item" href="{% url 'accounting:unit-download' format='csv' %}?model=income">CSV</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End top buttons -->

            <!-- Search -->
            <div class="container" style="padding: 0; padding-bottom: 1em;">
                <form id="id_search_form" method="get">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Income</label>
                            <input type="text" class="form-control" name="total_income" numval>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Receive date</label>
                            <input type="date" class="form-control" name="receive_date">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Created</label>
                            <input type="date" class="form-control" name="created">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Categories</label>
                        <select id="id_categories" class="form-control" name="categories" multiple>
                            {% for category in categories %}
                                <option>{{ category }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                    <a class="btn btn-light" href="{% url 'accounting:income-unit-list' %}">Show all</a>
                </form>
            </div>
            <!-- End search -->

            <!-- Table -->
            <table id="table" class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'name' '-' %}">Name
                                <img src="{% get_arrow request 'name' %}">
                            </a>
                        </th>

                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'quantity' '-' %}">Quantity
                                <img src="{% get_arrow request 'quantity' %}">
                            </a>
                        </th>

                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'total_income' '-' %}">Income
                                <img src="{% get_arrow request 'total_income' %}">
                            </a>
                        </th>

                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'receive_date' '-' %}">Receive date
                                <img src="{% get_arrow request 'receive_date' %}">
                            </a>
                        </th>

                        <th scope="col">
                            <a href="?{% order_by request 'order_by' 'created' '-' %}">Created
                                <img src="{% get_arrow request 'created' %}">
                            </a>
                        </th>

                        <th scope="col">Categories</th>
                    </tr>
                </thead>
                <tbody>
                    {% for unit in incomeunit_list %}
                    <tr>
                        <td>
                            <a href="{% url 'accounting:income-unit-update' pk=unit.pk %}">
                                {{ unit.name }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'accounting:income-unit-update' pk=unit.pk %}">
                                {{ unit.quantity }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'accounting:income-unit-update' pk=unit.pk %}">
                                ${{ unit.total_income }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'accounting:income-unit-update' pk=unit.pk %}">
                                {{ unit.receive_date }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'accounting:income-unit-update' pk=unit.pk %}">
                                {{ unit.created }}
                            </a>
                        </td>
                        <td>
                            {% for category in unit.categories.all %}
                                <a class="category" href="{% url 'accounting:category-detail' pk=category.pk %}">
                                    <span class="badge badge-info">{{ category }}</span>
                                </a>
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- End table -->

        <link href="{% static 'select2-4.1.0-rc.0/css/select2.min.css' %}" rel="stylesheet"/>
        <script src="{% static 'select2-4.1.0-rc.0/js/select2.min.js' %}"></script>
        <script src="{% static 'js/select2-init.js' %}"></script>
        <script src="{% static 'js/validate-numeric.js' %}"></script>
    </div>
{% endblock %}

templates/accounting/unit_detail.html
{% extends "base.html" %}

{% block title %}{{ unit.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="d-flex justify-content-end">
            <a href="{% url 'accounting:unit-update' pk=accountingunit.pk %}">edit</a>
        </div>
        <ul class="list-group">
            <li class="list-group-item">{{ accountingunit.name }}</li>
                <li class="list-group-item">
                    {% for category in accountingunit.categories.all %}
                        <a href="{% url 'accounting:category-detail' pk=category.pk %}">{{ category }}</a>
                    {% endfor %}
                </li>
            <li class="list-group-item">Price: {{ accountingunit.price }}</li>
            <li class="list-group-item">Purchased: {{ accountingunit.purchase_date }}</li>
            <li class="list-group-item">Created: {{ accountingunit.created }}</li>
        </ul>
    </div>
{% endblock %}