MyFinance/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='main'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path('statistics/', include('site_statistics.urls', namespace='statistics')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from accounts.views import RegistrationView, LoginView, LogoutView, AccountUpdateView, AccountDetailView

app_name = 'accounts'
urlpatterns = [
    path('', AccountDetailView.as_view(), name='account-detail'),
    path('update/', AccountUpdateView.as_view(), name='account-update'),
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils.functional import cached_property

from accounts.utils import user_directory_path


class User(AbstractUser):
    email = models.EmailField(max_length=256, unique=True)
    username = models.CharField(max_length=128, blank=True)
    avatar = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    job_position = models.CharField(max_length=64, blank=True)

    EMAIL_FIELD = "username"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []


class AccountManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related('user')


class Account(models.Model):
    monthly_salary = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    hourly_rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    hours_worked = models.PositiveIntegerField(blank=True, null=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    objects = AccountManager()

    @cached_property
    def calculate_total(self):
        total = 0
        if self.hourly_rate and self.hours_worked:
            total = self.hourly_rate * self.hours_worked
        elif self.monthly_salary:
            total = self.monthly_salary
        return total

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Account, User


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )
    password2 = forms.CharField(
        label=("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
    )

    class Meta:
        model = User
        fields = ['email', 'username']


class AccountUpdateForm(forms.ModelForm):
    monthly_salary = forms.DecimalField(
        required=False,
        help_text='Set either this or hourly rate',
        widget=forms.TextInput(attrs={'placeholder': '0.00', 'numval': ''})
        )

    hourly_rate = forms.DecimalField(
        required=False,
        help_text='Set either this or monthly salary',
        widget=forms.TextInput(attrs={'placeholder': '0.00', 'numval': ''})
        )

    hours_worked = forms.IntegerField(
        required=False,
        min_value=0,
        widget=forms.NumberInput(attrs={'placeholder': '0', 'numval': ''})
        )

    class Meta:
        model = Account
        fields = [
            'monthly_salary',
            'hourly_rate',
            'hours_worked',
        ]

UserForm = forms.modelform_factory(User, fields=('username', 'avatar', 'job_position'))

accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth import login, logout
from django.http import HttpResponseRedirect

from accounts.models import Account, User
from accounts.forms import RegistrationForm, AccountUpdateForm, UserForm


class UserRelatedMixin:
    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.request.user.pk)


class RegistrationView(CreateView):
    template_name = 'accounts/registration.html'
    model = User
    form_class = RegistrationForm
    success_url = reverse_lazy('accounts:account-detail')

    def form_valid(self, form):
        response = super().form_valid(form)
        Account.objects.create(user=self.object)
        login(self.request, self.object)
        return response


class LogoutView(LogoutView):
    next_page = reverse_lazy('main')


class LoginView(LoginView):
    template_name = 'accounts/login.html'
    next_page = reverse_lazy('main')
    redirect_authenticated_user = True


class AccountUpdateView(UserRelatedMixin, UpdateView):
    template_name = 'accounts/account_update.html'
    model = Account
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accounts:account-detail')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request == 'POST':
            context['user_form'] = UserForm(self.request.POST, instance=self.request.user)
        else:
            context['user_form'] = UserForm(instance=self.request.user)
        return context

    def form_valid(self, form):
        user_form = UserForm(self.request.POST, self.request.FILES, instance=self.request.user)
        if user_form.is_valid():
            user_form.save()
        return super().form_valid(form)


class AccountDetailView(UserRelatedMixin, DetailView):
    template_name = 'accounts/account_detail.html'
    model = Account

templates/accounts/account_detail.html
{% extends "base.html" %}

{% block title %}Account{% endblock %}

{% block content %}
    <div class="container">
        <div class="d-flex justify-content-end">
            <a href="{% url 'accounts:account-update' %}">edit</a>
        </div>
        <ul class="list-group">
            <li class="list-group-item">Username: {{ account.user.username }}</li>
            {% if account.user.avatar %}
                <li class="list-group-item">Avatar: <img src="{{ account.user.avatar.url }}" width="250"></li>
            {% endif %}
            <li class="list-group-item">
                Job position:
                {% if account.user.job_position %}
                    {{ account.user.job_position }}
                {% else %}
                    ---
                {% endif %}
            </li>
            <li class="list-group-item">
                Monthly salary:
                {% if account.monthly_salary %}
                    {{ account.monthly_salary }}
                {% else %}
                    ---
                {% endif %}
            </li>
            <li class="list-group-item">
                Hourly rate:
                {% if account.hourly_rate %}
                    {{ account.hourly_rate }}
                {% else %}
                    ---
                {% endif %}
            </li>
            <li class="list-group-item">
                Hours worked:
                {% if account.hours_worked %}
                    {{ account.hours_worked }}
                {% else %}
                    ---
                {% endif %}
            </li>
            <li class="list-group-item">
                Total earned: {{ account.calculate_total }}
            </li>
        </ul>
    </div>
{% endblock %}

templates/accounts/account_update.html
{% extends "base.html" %}

{% block title %}Update account{% endblock %}

{% block content %}
    {% load bootstrap4 %}
    {% load static %}

    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form user_form %}
            {% bootstrap_form form %}  
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                Submit
                </button>
            {% endbuttons %}
        </form>
    </div>

    <script src="{% static 'js/validate-numeric.js' %}"></script>
    <script src="{% static 'js/account-update.js' %}"></script>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Log In{% endblock %}

{% block content %}
    {% load bootstrap4 %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                Submit
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

templates/accounts/registration.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}
    {% load bootstrap4 %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                OK
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}