MyFinance/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='main'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path('statistics/', include('site_statistics.urls', namespace='statistics')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounting/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from accounting.views import (
    ExpensesUnitListView, ExpensesUnitCreateView, ExpensesUnitUpdateView,
    IncomeUnitCreateView, IncomeUnitUpdateView, IncomeUnitListView,
    UnitListView, AccountingDownloadView,
    CategoryCreateView, CategoryUpdateView, CategoryListView, CategoryDetailView,
    )

app_name = 'accounting'
urlpatterns = [
    path('', UnitListView.as_view(), name='unit-list'),

    path('expenses/', ExpensesUnitListView.as_view(), name='expenses-unit-list'),
    path('expenses_new/', ExpensesUnitCreateView.as_view(), name='expenses-unit-create'),
    path('expenses_edit/<int:pk>', ExpensesUnitUpdateView.as_view(), name='expenses-unit-update'),
    path('income/', IncomeUnitListView.as_view(), name='income-unit-list'),
    path('income_new/', IncomeUnitCreateView.as_view(), name='income-unit-create'),
    path('income_edit/<int:pk>', IncomeUnitUpdateView.as_view(), name='income-unit-update'),

    path('download/<str:format>', AccountingDownloadView.as_view(), name='unit-download'),

    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('category_new/', CategoryCreateView.as_view(), name='category-create'),
    path('category_edit/<int:pk>', CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path

from accounts.views import RegistrationView, LoginView, LogoutView, AccountUpdateView, AccountDetailView

app_name = 'accounts'
urlpatterns = [
    path('', AccountDetailView.as_view(), name='account-detail'),
    path('update/', AccountUpdateView.as_view(), name='account-update'),
    path('login/', LoginView.as_view(), name='login'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap-4.0.0-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.0.0-dist/js/bootstrap.min.js' %}"></script>
</head>
<body class="colors">
    <nav class="navbar navbar-expand-sm navbar-light bg-custom">
        <div class="expand navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main' %}">Main</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Accounting
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item dropright" href="{% url 'accounting:unit-list' %}?model=expenses">Accounting</a>
                <a class="dropdown-item dropright" href="{% url 'accounting:expenses-unit-list' %}">Expenses</a>
                <a class="dropdown-item dropright" href="{% url 'accounting:income-unit-list' %}">Income</a>
                <a class="dropdown-item" href="{% url 'accounting:category-list' %}">Categories</a>
                </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'statistics:main' %}">Statistics</a>
            </li>
          </ul>
        </div>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.avatar %}<img class="avatar navbar-left" src="{{ user.avatar.url }}">{% endif %}{{ user.email }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'accounts:account-detail' %}">Account</a>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
              </div>
            </li>
            {% else %}
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              <a class="nav-link" href="{% url 'accounts:registration' %}">Registration</a>
            {% endif %}
          </ul>
        </div>
      </nav>

    {% block content %}{% endblock %}
    
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Main{% endblock %}

{% block content %}
{% endblock %}